Import ('env')

env.Append(CXXFLAGS=['--std=c++0x'])

name = 'fideo'
inc = env.Dir('.')
src = env.Glob('*.cpp')
deps = ['etilico', 'biopp', 'gtest_main', 'gtest', 'gmock']

env.CreateTest(name, inc, src, deps)
